#!/usr/bin/env bash
# Launch the app with --dart-define vars loaded from .env
# Usage: ./scripts/run.sh [platform|device-id|number] [extra flutter args...]
#
# Injects GOOGLE_MAPS_API_KEY from .env into every platform:
#   Dart (all)  → --dart-define-from-file=.env
#   Android     → android/gradle.properties  → manifestPlaceholders in build.gradle.kts
#   iOS         → ios/Flutter/Secrets.xcconfig  → $(GOOGLE_MAPS_API_KEY) in Info.plist
#   Web         → web/google_maps_config.js     → window.GOOGLE_MAPS_API_KEY
#   macOS       → --dart-define-from-file only  (flutter_map OSM fallback on desktop)
#
# Examples:
#   ./scripts/run.sh                            # interactive device picker
#   ./scripts/run.sh 1                          # pick device/emulator #1 from list
#   ./scripts/run.sh chrome                     # web on Chrome
#   ./scripts/run.sh --release                  # interactive picker + release flag
#   ./scripts/run.sh macos --debug              # macOS desktop with debug flag

set -euo pipefail
cd "$(dirname "$0")/.."

# ── Dependencies ─────────────────────────────────────────────────────────────
if ! command -v flutter >/dev/null 2>&1; then
  echo "Error: flutter command not found in PATH."
  exit 1
fi

# ── .env check ───────────────────────────────────────────────────────────────
ENV_FILE=".env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found."
  echo "  cp .env.example .env   # then fill in your keys"
  exit 1
fi

# ── Read Google Maps API key from .env (if present) ─────────────────────────
GOOGLE_MAPS_API_KEY_VALUE=""
if grep -q '^GOOGLE_MAPS_API_KEY=' "$ENV_FILE"; then
  # Extract value and strip quotes (single or double)
  GOOGLE_MAPS_API_KEY_VALUE="$(grep '^GOOGLE_MAPS_API_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")"
fi

# ── Platform config paths ───────────────────────────────────────────────────
ANDROID_PROPS="android/gradle.properties"
IOS_SECRETS_XCCONFIG="ios/Flutter/Secrets.xcconfig"
WEB_MAPS_CONFIG="web/google_maps_config.js"

# ── Cleanup: remove generated secret files on exit ──────────────────────────
cleanup() {
  # Remove key from android/gradle.properties (if added)
  if [[ -f "$ANDROID_PROPS" ]]; then
    # Create a clean version without the key and without trailing empty lines added by us
    grep -v "^GOOGLE_MAPS_API_KEY=" "$ANDROID_PROPS" > "${ANDROID_PROPS}.tmp" || true
    mv "${ANDROID_PROPS}.tmp" "$ANDROID_PROPS"
  fi

  rm -f "$IOS_SECRETS_XCCONFIG"
  rm -f "$WEB_MAPS_CONFIG"
}
trap cleanup EXIT

# ── Inject key into platform configs ────────────────────────────────────────
if [[ -n "$GOOGLE_MAPS_API_KEY_VALUE" ]]; then
  echo "  ✔ GOOGLE_MAPS_API_KEY found in .env"

  # Android – Update gradle.properties
  if [[ -f "$ANDROID_PROPS" ]]; then
    # Ensure key isn't already there (clean start)
    grep -v "^GOOGLE_MAPS_API_KEY=" "$ANDROID_PROPS" > "${ANDROID_PROPS}.tmp" || true
    mv "${ANDROID_PROPS}.tmp" "$ANDROID_PROPS"
    # Append key
    echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY_VALUE}" >> "$ANDROID_PROPS"
  fi

  # iOS – write gitignored Secrets.xcconfig
  cat > "$IOS_SECRETS_XCCONFIG" <<EOF
// Auto-generated by scripts/run.sh — do NOT commit this file.
GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY_VALUE}
EOF

  # Web – runtime JS config loaded by index.html / flutter_bootstrap.js
  cat > "$WEB_MAPS_CONFIG" <<EOF
window.GOOGLE_MAPS_API_KEY = "${GOOGLE_MAPS_API_KEY_VALUE}";
EOF
else
  echo "  ⚠ GOOGLE_MAPS_API_KEY not set in .env — maps may be unavailable"
fi

# ── Helpers ─────────────────────────────────────────────────────────────────
get_devices() {
  flutter devices 2>/dev/null | grep '•' | grep -v '^$' || true
}

get_emulators() {
  flutter emulators 2>/dev/null | grep '•' | grep -v '^Id' | grep -v '^$' || true
}

emulator_id_from_line() {
  echo "$1" | awk -F '•' '{print $1}' | xargs
}

device_contains_platform() {
  local devices="$1"
  local keyword="$2"
  printf "%s\n" "$devices" | grep -qi "$keyword"
}

# ── Argument Parsing ────────────────────────────────────────────────────────
DEVICE_ARG=""
EXTRA_ARGS=()

# If the first argument is NOT a flag (doesn't start with -), treat it as a target
if [[ $# -gt 0 ]] && [[ ! "$1" =~ ^- ]]; then
  FIRST_ARG="$1"
  shift
  EXTRA_ARGS=("$@")

  # Check if numeric selection
  if [[ "$FIRST_ARG" =~ ^[0-9]+$ ]] && [[ "$FIRST_ARG" -gt 0 ]]; then
    DEVICES="$(get_devices)"
    EMULATORS="$(get_emulators)"

    DEVICE_COUNT=0
    if [[ -n "$DEVICES" ]]; then
      DEVICE_COUNT="$(printf "%s\n" "$DEVICES" | wc -l | xargs)"
    fi

    FILTERED_EMULATORS=""
    if [[ -n "$EMULATORS" ]]; then
      while IFS= read -r emu_line; do
        emu_platform="$(echo "$emu_line" | awk -F '•' '{print $4}' | xargs)"
        if [[ "$emu_platform" == "android" ]] && device_contains_platform "$DEVICES" "android"; then continue; fi
        if [[ "$emu_platform" == "ios" ]] && device_contains_platform "$DEVICES" "ios"; then continue; fi
        
        if [[ -n "$FILTERED_EMULATORS" ]]; then
          FILTERED_EMULATORS="${FILTERED_EMULATORS}\n${emu_line}"
        else
          FILTERED_EMULATORS="$emu_line"
        fi
      done <<< "$EMULATORS"
    fi

    EMU_COUNT=0
    if [[ -n "$FILTERED_EMULATORS" ]]; then
      EMU_COUNT="$(printf "%b\n" "$FILTERED_EMULATORS" | wc -l | xargs)"
    fi

    TOTAL=$((DEVICE_COUNT + EMU_COUNT))
    if [[ "$FIRST_ARG" -gt "$TOTAL" ]]; then
      echo "  ✗ Option #${FIRST_ARG} not found (only $TOTAL available)."
      exit 1
    fi

    if [[ "$FIRST_ARG" -le "$DEVICE_COUNT" ]]; then
      DEVICE_LINE="$(printf "%s\n" "$DEVICES" | sed -n "${FIRST_ARG}p")"
      DEVICE_ID="$(echo "$DEVICE_LINE" | awk -F '•' '{print $2}' | xargs)"
      echo "  ℹ Selected device #${FIRST_ARG}: $DEVICE_LINE"
      DEVICE_ARG="-d $DEVICE_ID"
    else
      EMU_INDEX=$((FIRST_ARG - DEVICE_COUNT))
      EMU_LINE="$(printf "%b\n" "$FILTERED_EMULATORS" | sed -n "${EMU_INDEX}p")"
      EMU_ID="$(emulator_id_from_line "$EMU_LINE")"
      echo "  ℹ Launching emulator: $EMU_LINE"
      flutter emulators --launch "$EMU_ID"
      echo "  ⏳ Waiting for device..."
      sleep 8
      DEVICES="$(get_devices)"
      EMU_PLATFORM="$(echo "$EMU_LINE" | awk -F '•' '{print $4}' | xargs)"
      if [[ "$EMU_PLATFORM" == "ios" ]]; then
        DEVICE_LINE="$(printf "%s\n" "$DEVICES" | grep -i 'iphone\|ipad\|simulator.*ios' | head -1)" || true
      else
        DEVICE_LINE="$(printf "%s\n" "$DEVICES" | grep -i 'android\|emulator\|sdk' | head -1)" || true
      fi
      if [[ -z "$DEVICE_LINE" ]]; then
        echo "  ✗ Device not detected after launch."
        exit 1
      fi
      DEVICE_ID="$(echo "$DEVICE_LINE" | awk -F '•' '{print $2}' | xargs)"
      DEVICE_ARG="-d $DEVICE_ID"
    fi
  else
    # Direct target string
    DEVICE_ARG="-d $FIRST_ARG"
  fi
else
  # No target specified or flags only — trigger interactive picker
  EXTRA_ARGS=("$@")
  
  echo ""
  echo "╔══════════════════════════════════════════════════════════════════╗"
  echo "║                    MQ Navigation — Run                         ║"
  echo "╚══════════════════════════════════════════════════════════════════╝"
  echo ""
  echo "Scanning for targets..."
  echo ""

  DEVICES="$(get_devices)"
  EMULATORS="$(get_emulators)"

  DEVICE_COUNT=0
  if [[ -n "$DEVICES" ]]; then
    DEVICE_COUNT="$(printf "%s\n" "$DEVICES" | wc -l | xargs)"
  fi

  FILTERED_EMULATORS=""
  if [[ -n "$EMULATORS" ]]; then
    while IFS= read -r emu_line; do
      emu_platform="$(echo "$emu_line" | awk -F '•' '{print $4}' | xargs)"
      if [[ "$emu_platform" == "android" ]] && device_contains_platform "$DEVICES" "android"; then continue; fi
      if [[ "$emu_platform" == "ios" ]] && device_contains_platform "$DEVICES" "ios"; then continue; fi
      
      if [[ -n "$FILTERED_EMULATORS" ]]; then
        FILTERED_EMULATORS="${FILTERED_EMULATORS}\n${emu_line}"
      else
        FILTERED_EMULATORS="$emu_line"
      fi
    done <<< "$EMULATORS"
  fi

  EMU_COUNT=0
  if [[ -n "$FILTERED_EMULATORS" ]]; then
    EMU_COUNT="$(printf "%b\n" "$FILTERED_EMULATORS" | wc -l | xargs)"
  fi

  TOTAL=$((DEVICE_COUNT + EMU_COUNT))

  if [[ "$TOTAL" -eq 0 ]]; then
    echo "  ✗ No targets found."
    exit 1
  fi

  echo "  Available targets:"
  echo "  ─────────────────────────────────────────────────────────────────"
  INDEX=1
  if [[ -n "$DEVICES" ]]; then
    echo "  Running devices:"
    while IFS= read -r line; do
      printf "  %2d)  %s\n" "$INDEX" "$line"
      INDEX=$((INDEX + 1))
    done <<< "$DEVICES"
  fi
  if [[ -n "$FILTERED_EMULATORS" ]]; then
    echo ""
    echo "  Available emulators:"
    while IFS= read -r line; do
      printf "  %2d)  🚀 %s\n" "$INDEX" "$line"
      INDEX=$((INDEX + 1))
    done <<< "$(printf "%b\n" "$FILTERED_EMULATORS")"
  fi
  echo "  ─────────────────────────────────────────────────────────────────"
  echo ""
  printf "  Select [1-%s]: " "$TOTAL"
  read -r SELECTION

  if [[ ! "$SELECTION" =~ ^[0-9]+$ ]] || [[ "$SELECTION" -lt 1 ]] || [[ "$SELECTION" -gt "$TOTAL" ]]; then
    echo "  ✗ Invalid selection."
    exit 1
  fi

  if [[ "$SELECTION" -le "$DEVICE_COUNT" ]]; then
    DEVICE_LINE="$(printf "%s\n" "$DEVICES" | sed -n "${SELECTION}p")"
    DEVICE_ID="$(echo "$DEVICE_LINE" | awk -F '•' '{print $2}' | xargs)"
    DEVICE_ARG="-d $DEVICE_ID"
  else
    EMU_INDEX=$((SELECTION - DEVICE_COUNT))
    EMU_LINE="$(printf "%b\n" "$FILTERED_EMULATORS" | sed -n "${EMU_INDEX}p")"
    EMU_ID="$(emulator_id_from_line "$EMU_LINE")"
    EMU_PLATFORM="$(echo "$EMU_LINE" | awk -F '•' '{print $4}' | xargs)"
    echo ""
    echo "  🚀 Launching: $EMU_LINE"
    flutter emulators --launch "$EMU_ID"
    echo ""
    echo -n "  ⏳ Waiting for device"
    MAX_WAIT=60
    ELAPSED=0
    DEVICE_LINE=""
    while [[ $ELAPSED -lt $MAX_WAIT ]]; do
      sleep 3
      ELAPSED=$((ELAPSED + 3))
      DEVICES="$(get_devices)"
      if [[ "$EMU_PLATFORM" == "ios" ]]; then
        DEVICE_LINE="$(printf "%s\n" "$DEVICES" | grep -i 'iphone\|ipad\|simulator.*ios' | head -1)" || true
      else
        DEVICE_LINE="$(printf "%s\n" "$DEVICES" | grep -i 'android\|emulator\|sdk\|pixel' | head -1)" || true
      fi
      if [[ -n "$DEVICE_LINE" ]]; then break; fi
      echo -n "."
    done
    echo ""
    if [[ -z "$DEVICE_LINE" ]]; then echo "  ✗ Timed out."; exit 1; fi
    DEVICE_ID="$(echo "$DEVICE_LINE" | awk -F '•' '{print $2}' | xargs)"
    DEVICE_ARG="-d $DEVICE_ID"
  fi
fi

echo ""
echo "Launching with dart-defines from .env..."
export MACOSX_DEPLOYMENT_TARGET=13.0
flutter run $DEVICE_ARG --dart-define-from-file="$ENV_FILE" ${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"}
