#!/usr/bin/env bash
# Launch the app with --dart-define vars loaded from .env
# Usage: ./scripts/run.sh [device-id] [extra flutter args...]
#
# Injects GOOGLE_MAPS_API_KEY from .env into every platform:
#   Dart (all)  → --dart-define-from-file=.env
#   Android     → GOOGLE_MAPS_API_KEY env var  → System.getenv() in build.gradle.kts
#   iOS         → ios/Flutter/Secrets.xcconfig  → $(GOOGLE_MAPS_API_KEY) in Info.plist
#   Web         → web/google_maps_config.js     → window.GOOGLE_MAPS_API_KEY
#   macOS       → --dart-define-from-file only  (no native Google Maps SDK)
#
# Examples:
#   ./scripts/run.sh                            # pick device interactively
#   ./scripts/run.sh 00008150-000E7C6A1EF0401C  # specific device
#   ./scripts/run.sh chrome
#   ./scripts/run.sh macos

set -euo pipefail
cd "$(dirname "$0")/.."

# ── .env check ───────────────────────────────────────────────────────────────
ENV_FILE=".env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Error: $ENV_FILE not found."
  echo "  cp .env.example .env   # then fill in your keys"
  exit 1
fi

# ── Read Google Maps API key from .env (if present) ─────────────────────────
GOOGLE_MAPS_API_KEY_VALUE=""
if grep -q '^GOOGLE_MAPS_API_KEY=' "$ENV_FILE"; then
  GOOGLE_MAPS_API_KEY_VALUE="$(grep '^GOOGLE_MAPS_API_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2-)"
fi

# ── Platform config paths ───────────────────────────────────────────────────
IOS_SECRETS_XCCONFIG="ios/Flutter/Secrets.xcconfig"
WEB_MAPS_CONFIG="web/google_maps_config.js"

# ── Cleanup: remove generated secret files on exit ──────────────────────────
cleanup() {
  rm -f "$IOS_SECRETS_XCCONFIG"
  rm -f "$WEB_MAPS_CONFIG"
}
trap cleanup EXIT

# ── Inject key into platform configs ────────────────────────────────────────
if [[ -n "$GOOGLE_MAPS_API_KEY_VALUE" ]]; then
  echo "  ✔ GOOGLE_MAPS_API_KEY found in .env"

  # Android – export env var → build.gradle.kts reads via System.getenv()
  export GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY_VALUE"

  # iOS – write gitignored Secrets.xcconfig → #include?'d by Debug/Release.xcconfig
  #        → resolved as $(GOOGLE_MAPS_API_KEY) in Info.plist → AppDelegate
  cat > "$IOS_SECRETS_XCCONFIG" <<EOF
// Auto-generated by scripts/run.sh — do NOT commit this file.
GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY_VALUE}
EOF

  # Web – runtime JS config loaded by index.html / flutter_bootstrap.js
  cat > "$WEB_MAPS_CONFIG" <<EOF
window.GOOGLE_MAPS_API_KEY = "${GOOGLE_MAPS_API_KEY_VALUE}";
EOF
else
  echo "  ⚠ GOOGLE_MAPS_API_KEY not set in .env — maps may be unavailable"
fi

# ── Parse device argument ───────────────────────────────────────────────────
DEVICE_ARG=""
if [[ -n "${1:-}" ]]; then
  DEVICE_ARG="-d $1"
  shift
fi

echo "Launching with dart-defines from .env..."
export MACOSX_DEPLOYMENT_TARGET=11.0
flutter run $DEVICE_ARG --dart-define-from-file="$ENV_FILE" "$@"
